/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_1 */
#define Pin_1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_0_INBUF_ENABLED 0u
#define Pin_1_0_INIT_DRIVESTATE 1u
#define Pin_1_0_INIT_MUXSEL 0u
#define Pin_1_0_INPUT_SYNC 2u
#define Pin_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_0_NUM 0u
#define Pin_1_0_PORT GPIO_PRT10
#define Pin_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_INBUF_ENABLED 0u
#define Pin_1_INIT_DRIVESTATE 1u
#define Pin_1_INIT_MUXSEL 0u
#define Pin_1_INPUT_SYNC 2u
#define Pin_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_NUM 0u
#define Pin_1_PORT GPIO_PRT10
#define Pin_1_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_2 */
#define Pin_2_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_2_0_INBUF_ENABLED 0u
#define Pin_2_0_INIT_DRIVESTATE 1u
#define Pin_2_0_INIT_MUXSEL 5u
#define Pin_2_0_INPUT_SYNC 2u
#define Pin_2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_2_0_NUM 1u
#define Pin_2_0_PORT GPIO_PRT7
#define Pin_2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_2_INBUF_ENABLED 0u
#define Pin_2_INIT_DRIVESTATE 1u
#define Pin_2_INIT_MUXSEL 5u
#define Pin_2_INPUT_SYNC 2u
#define Pin_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_2_NUM 1u
#define Pin_2_PORT GPIO_PRT7
#define Pin_2_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_3 */
#define Pin_3_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Pin_3_0_INBUF_ENABLED 1u
#define Pin_3_0_INIT_DRIVESTATE 0u
#define Pin_3_0_INIT_MUXSEL 0u
#define Pin_3_0_INPUT_SYNC 2u
#define Pin_3_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_3_0_NUM 2u
#define Pin_3_0_PORT GPIO_PRT5
#define Pin_3_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_3_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_3_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Pin_3_INBUF_ENABLED 1u
#define Pin_3_INIT_DRIVESTATE 0u
#define Pin_3_INIT_MUXSEL 0u
#define Pin_3_INPUT_SYNC 2u
#define Pin_3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_3_NUM 2u
#define Pin_3_PORT GPIO_PRT5
#define Pin_3_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* StimEN */
#define StimEN_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define StimEN_0_INBUF_ENABLED 0u
#define StimEN_0_INIT_DRIVESTATE 0u
#define StimEN_0_INIT_MUXSEL 0u
#define StimEN_0_INPUT_SYNC 2u
#define StimEN_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define StimEN_0_NUM 0u
#define StimEN_0_PORT GPIO_PRT0
#define StimEN_0_SLEWRATE CY_GPIO_SLEW_FAST
#define StimEN_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define StimEN_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define StimEN_INBUF_ENABLED 0u
#define StimEN_INIT_DRIVESTATE 0u
#define StimEN_INIT_MUXSEL 0u
#define StimEN_INPUT_SYNC 2u
#define StimEN_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define StimEN_NUM 0u
#define StimEN_PORT GPIO_PRT0
#define StimEN_SLEWRATE CY_GPIO_SLEW_FAST
#define StimEN_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Dummy_load */
#define Dummy_load_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Dummy_load_0_INBUF_ENABLED 0u
#define Dummy_load_0_INIT_DRIVESTATE 0u
#define Dummy_load_0_INIT_MUXSEL 0u
#define Dummy_load_0_INPUT_SYNC 2u
#define Dummy_load_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Dummy_load_0_NUM 5u
#define Dummy_load_0_PORT GPIO_PRT0
#define Dummy_load_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Dummy_load_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Dummy_load_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Dummy_load_INBUF_ENABLED 0u
#define Dummy_load_INIT_DRIVESTATE 0u
#define Dummy_load_INIT_MUXSEL 0u
#define Dummy_load_INPUT_SYNC 2u
#define Dummy_load_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Dummy_load_NUM 5u
#define Dummy_load_PORT GPIO_PRT0
#define Dummy_load_SLEWRATE CY_GPIO_SLEW_FAST
#define Dummy_load_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Toggle_output */
#define Toggle_output_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Toggle_output_0_INBUF_ENABLED 0u
#define Toggle_output_0_INIT_DRIVESTATE 0u
#define Toggle_output_0_INIT_MUXSEL 0u
#define Toggle_output_0_INPUT_SYNC 2u
#define Toggle_output_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Toggle_output_0_NUM 1u
#define Toggle_output_0_PORT GPIO_PRT0
#define Toggle_output_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Toggle_output_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Toggle_output_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Toggle_output_INBUF_ENABLED 0u
#define Toggle_output_INIT_DRIVESTATE 0u
#define Toggle_output_INIT_MUXSEL 0u
#define Toggle_output_INPUT_SYNC 2u
#define Toggle_output_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Toggle_output_NUM 1u
#define Toggle_output_PORT GPIO_PRT0
#define Toggle_output_SLEWRATE CY_GPIO_SLEW_FAST
#define Toggle_output_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Short_electrode */
#define Short_electrode_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Short_electrode_0_INBUF_ENABLED 0u
#define Short_electrode_0_INIT_DRIVESTATE 0u
#define Short_electrode_0_INIT_MUXSEL 0u
#define Short_electrode_0_INPUT_SYNC 2u
#define Short_electrode_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Short_electrode_0_NUM 4u
#define Short_electrode_0_PORT GPIO_PRT0
#define Short_electrode_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Short_electrode_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Short_electrode_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Short_electrode_INBUF_ENABLED 0u
#define Short_electrode_INIT_DRIVESTATE 0u
#define Short_electrode_INIT_MUXSEL 0u
#define Short_electrode_INPUT_SYNC 2u
#define Short_electrode_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Short_electrode_NUM 4u
#define Short_electrode_PORT GPIO_PRT0
#define Short_electrode_SLEWRATE CY_GPIO_SLEW_FAST
#define Short_electrode_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
