/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* RED */
#define RED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_0_INBUF_ENABLED 0u
#define RED_0_INIT_DRIVESTATE 1u
#define RED_0_INIT_MUXSEL 8u
#define RED_0_INPUT_SYNC 2u
#define RED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_0_NUM 4u
#define RED_0_PORT GPIO_PRT0
#define RED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RED_INBUF_ENABLED 0u
#define RED_INIT_DRIVESTATE 1u
#define RED_INIT_MUXSEL 8u
#define RED_INPUT_SYNC 2u
#define RED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_NUM 4u
#define RED_PORT GPIO_PRT0
#define RED_SLEWRATE CY_GPIO_SLEW_FAST
#define RED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* GREEN */
#define GREEN_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GREEN_0_INBUF_ENABLED 0u
#define GREEN_0_INIT_DRIVESTATE 1u
#define GREEN_0_INIT_MUXSEL 8u
#define GREEN_0_INPUT_SYNC 2u
#define GREEN_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GREEN_0_NUM 2u
#define GREEN_0_PORT GPIO_PRT6
#define GREEN_0_SLEWRATE CY_GPIO_SLEW_FAST
#define GREEN_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define GREEN_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GREEN_INBUF_ENABLED 0u
#define GREEN_INIT_DRIVESTATE 1u
#define GREEN_INIT_MUXSEL 8u
#define GREEN_INPUT_SYNC 2u
#define GREEN_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GREEN_NUM 2u
#define GREEN_PORT GPIO_PRT6
#define GREEN_SLEWRATE CY_GPIO_SLEW_FAST
#define GREEN_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* dac_out */
#define dac_out_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define dac_out_0_INBUF_ENABLED 0u
#define dac_out_0_INIT_DRIVESTATE 1u
#define dac_out_0_INIT_MUXSEL 4u
#define dac_out_0_INPUT_SYNC 2u
#define dac_out_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define dac_out_0_NUM 0u
#define dac_out_0_PORT GPIO_PRT10
#define dac_out_0_SLEWRATE CY_GPIO_SLEW_FAST
#define dac_out_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define dac_out_DRIVEMODE CY_GPIO_DM_ANALOG
#define dac_out_INBUF_ENABLED 0u
#define dac_out_INIT_DRIVESTATE 1u
#define dac_out_INIT_MUXSEL 4u
#define dac_out_INPUT_SYNC 2u
#define dac_out_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define dac_out_NUM 0u
#define dac_out_PORT GPIO_PRT10
#define dac_out_SLEWRATE CY_GPIO_SLEW_FAST
#define dac_out_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 0u
#define UART_1_rx_0_PORT GPIO_PRT5
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 0u
#define UART_1_rx_PORT GPIO_PRT5
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 1u
#define UART_1_tx_0_PORT GPIO_PRT5
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 1u
#define UART_1_tx_PORT GPIO_PRT5
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Dummy_Load */
#define Dummy_Load_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Dummy_Load_0_INBUF_ENABLED 0u
#define Dummy_Load_0_INIT_DRIVESTATE 0u
#define Dummy_Load_0_INIT_MUXSEL 0u
#define Dummy_Load_0_INPUT_SYNC 2u
#define Dummy_Load_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Dummy_Load_0_NUM 0u
#define Dummy_Load_0_PORT GPIO_PRT9
#define Dummy_Load_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Dummy_Load_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Dummy_Load_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Dummy_Load_INBUF_ENABLED 0u
#define Dummy_Load_INIT_DRIVESTATE 0u
#define Dummy_Load_INIT_MUXSEL 0u
#define Dummy_Load_INPUT_SYNC 2u
#define Dummy_Load_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Dummy_Load_NUM 0u
#define Dummy_Load_PORT GPIO_PRT9
#define Dummy_Load_SLEWRATE CY_GPIO_SLEW_FAST
#define Dummy_Load_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* VDAC_Out_1 */
#define VDAC_Out_1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define VDAC_Out_1_0_INBUF_ENABLED 0u
#define VDAC_Out_1_0_INIT_DRIVESTATE 1u
#define VDAC_Out_1_0_INIT_MUXSEL 4u
#define VDAC_Out_1_0_INPUT_SYNC 2u
#define VDAC_Out_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VDAC_Out_1_0_NUM 1u
#define VDAC_Out_1_0_PORT GPIO_PRT7
#define VDAC_Out_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define VDAC_Out_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define VDAC_Out_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define VDAC_Out_1_INBUF_ENABLED 0u
#define VDAC_Out_1_INIT_DRIVESTATE 1u
#define VDAC_Out_1_INIT_MUXSEL 4u
#define VDAC_Out_1_INPUT_SYNC 2u
#define VDAC_Out_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VDAC_Out_1_NUM 1u
#define VDAC_Out_1_PORT GPIO_PRT7
#define VDAC_Out_1_SLEWRATE CY_GPIO_SLEW_FAST
#define VDAC_Out_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Stim_Enable */
#define Stim_Enable_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Stim_Enable_0_INBUF_ENABLED 0u
#define Stim_Enable_0_INIT_DRIVESTATE 0u
#define Stim_Enable_0_INIT_MUXSEL 0u
#define Stim_Enable_0_INPUT_SYNC 2u
#define Stim_Enable_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Stim_Enable_0_NUM 3u
#define Stim_Enable_0_PORT GPIO_PRT9
#define Stim_Enable_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Stim_Enable_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Stim_Enable_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Stim_Enable_INBUF_ENABLED 0u
#define Stim_Enable_INIT_DRIVESTATE 0u
#define Stim_Enable_INIT_MUXSEL 0u
#define Stim_Enable_INPUT_SYNC 2u
#define Stim_Enable_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Stim_Enable_NUM 3u
#define Stim_Enable_PORT GPIO_PRT9
#define Stim_Enable_SLEWRATE CY_GPIO_SLEW_FAST
#define Stim_Enable_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Toggle_Output */
#define Toggle_Output_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Toggle_Output_0_INBUF_ENABLED 0u
#define Toggle_Output_0_INIT_DRIVESTATE 0u
#define Toggle_Output_0_INIT_MUXSEL 0u
#define Toggle_Output_0_INPUT_SYNC 2u
#define Toggle_Output_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Toggle_Output_0_NUM 2u
#define Toggle_Output_0_PORT GPIO_PRT9
#define Toggle_Output_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Toggle_Output_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Toggle_Output_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Toggle_Output_INBUF_ENABLED 0u
#define Toggle_Output_INIT_DRIVESTATE 0u
#define Toggle_Output_INIT_MUXSEL 0u
#define Toggle_Output_INPUT_SYNC 2u
#define Toggle_Output_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Toggle_Output_NUM 2u
#define Toggle_Output_PORT GPIO_PRT9
#define Toggle_Output_SLEWRATE CY_GPIO_SLEW_FAST
#define Toggle_Output_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Short_Electrode */
#define Short_Electrode_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Short_Electrode_0_INBUF_ENABLED 0u
#define Short_Electrode_0_INIT_DRIVESTATE 0u
#define Short_Electrode_0_INIT_MUXSEL 0u
#define Short_Electrode_0_INPUT_SYNC 2u
#define Short_Electrode_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Short_Electrode_0_NUM 1u
#define Short_Electrode_0_PORT GPIO_PRT9
#define Short_Electrode_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Short_Electrode_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Short_Electrode_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Short_Electrode_INBUF_ENABLED 0u
#define Short_Electrode_INIT_DRIVESTATE 0u
#define Short_Electrode_INIT_MUXSEL 0u
#define Short_Electrode_INPUT_SYNC 2u
#define Short_Electrode_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Short_Electrode_NUM 1u
#define Short_Electrode_PORT GPIO_PRT9
#define Short_Electrode_SLEWRATE CY_GPIO_SLEW_FAST
#define Short_Electrode_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
