/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* VDAC_Out_P9_6 */
#define VDAC_Out_P9_6_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define VDAC_Out_P9_6_0_INBUF_ENABLED 0u
#define VDAC_Out_P9_6_0_INIT_DRIVESTATE 1u
#define VDAC_Out_P9_6_0_INIT_MUXSEL 0u
#define VDAC_Out_P9_6_0_INPUT_SYNC 2u
#define VDAC_Out_P9_6_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VDAC_Out_P9_6_0_NUM 6u
#define VDAC_Out_P9_6_0_PORT GPIO_PRT9
#define VDAC_Out_P9_6_0_SLEWRATE CY_GPIO_SLEW_FAST
#define VDAC_Out_P9_6_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define VDAC_Out_P9_6_DRIVEMODE CY_GPIO_DM_ANALOG
#define VDAC_Out_P9_6_INBUF_ENABLED 0u
#define VDAC_Out_P9_6_INIT_DRIVESTATE 1u
#define VDAC_Out_P9_6_INIT_MUXSEL 0u
#define VDAC_Out_P9_6_INPUT_SYNC 2u
#define VDAC_Out_P9_6_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define VDAC_Out_P9_6_NUM 6u
#define VDAC_Out_P9_6_PORT GPIO_PRT9
#define VDAC_Out_P9_6_SLEWRATE CY_GPIO_SLEW_FAST
#define VDAC_Out_P9_6_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
