/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* BLINKYMF */
#define BLINKYMF_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BLINKYMF_0_INBUF_ENABLED 0u
#define BLINKYMF_0_INIT_DRIVESTATE 0u
#define BLINKYMF_0_INIT_MUXSEL 0u
#define BLINKYMF_0_INPUT_SYNC 2u
#define BLINKYMF_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BLINKYMF_0_NUM 3u
#define BLINKYMF_0_PORT GPIO_PRT6
#define BLINKYMF_0_SLEWRATE CY_GPIO_SLEW_FAST
#define BLINKYMF_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define BLINKYMF_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BLINKYMF_INBUF_ENABLED 0u
#define BLINKYMF_INIT_DRIVESTATE 0u
#define BLINKYMF_INIT_MUXSEL 0u
#define BLINKYMF_INPUT_SYNC 2u
#define BLINKYMF_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BLINKYMF_NUM 3u
#define BLINKYMF_PORT GPIO_PRT6
#define BLINKYMF_SLEWRATE CY_GPIO_SLEW_FAST
#define BLINKYMF_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
