/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* BLINKY1 */
#define BLINKY1_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BLINKY1_0_INBUF_ENABLED 0u
#define BLINKY1_0_INIT_DRIVESTATE 0u
#define BLINKY1_0_INIT_MUXSEL 0u
#define BLINKY1_0_INPUT_SYNC 2u
#define BLINKY1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BLINKY1_0_NUM 1u
#define BLINKY1_0_PORT GPIO_PRT7
#define BLINKY1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define BLINKY1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define BLINKY1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BLINKY1_INBUF_ENABLED 0u
#define BLINKY1_INIT_DRIVESTATE 0u
#define BLINKY1_INIT_MUXSEL 0u
#define BLINKY1_INPUT_SYNC 2u
#define BLINKY1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BLINKY1_NUM 1u
#define BLINKY1_PORT GPIO_PRT7
#define BLINKY1_SLEWRATE CY_GPIO_SLEW_FAST
#define BLINKY1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* BLINKY2 */
#define BLINKY2_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BLINKY2_0_INBUF_ENABLED 0u
#define BLINKY2_0_INIT_DRIVESTATE 0u
#define BLINKY2_0_INIT_MUXSEL 0u
#define BLINKY2_0_INPUT_SYNC 2u
#define BLINKY2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BLINKY2_0_NUM 3u
#define BLINKY2_0_PORT GPIO_PRT6
#define BLINKY2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define BLINKY2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define BLINKY2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BLINKY2_INBUF_ENABLED 0u
#define BLINKY2_INIT_DRIVESTATE 0u
#define BLINKY2_INIT_MUXSEL 0u
#define BLINKY2_INPUT_SYNC 2u
#define BLINKY2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define BLINKY2_NUM 3u
#define BLINKY2_PORT GPIO_PRT6
#define BLINKY2_SLEWRATE CY_GPIO_SLEW_FAST
#define BLINKY2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
