/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* DAC_out */
#define DAC_out_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define DAC_out_0_INBUF_ENABLED 0u
#define DAC_out_0_INIT_DRIVESTATE 1u
#define DAC_out_0_INIT_MUXSEL 4u
#define DAC_out_0_INPUT_SYNC 2u
#define DAC_out_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DAC_out_0_NUM 0u
#define DAC_out_0_PORT GPIO_PRT10
#define DAC_out_0_SLEWRATE CY_GPIO_SLEW_FAST
#define DAC_out_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define DAC_out_DRIVEMODE CY_GPIO_DM_ANALOG
#define DAC_out_INBUF_ENABLED 0u
#define DAC_out_INIT_DRIVESTATE 1u
#define DAC_out_INIT_MUXSEL 4u
#define DAC_out_INPUT_SYNC 2u
#define DAC_out_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DAC_out_NUM 0u
#define DAC_out_PORT GPIO_PRT10
#define DAC_out_SLEWRATE CY_GPIO_SLEW_FAST
#define DAC_out_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 0u
#define UART_1_rx_0_PORT GPIO_PRT5
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 0u
#define UART_1_rx_PORT GPIO_PRT5
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 1u
#define UART_1_tx_0_PORT GPIO_PRT5
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 1u
#define UART_1_tx_PORT GPIO_PRT5
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* DAC_to_ADC */
#define DAC_to_ADC_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define DAC_to_ADC_0_INBUF_ENABLED 0u
#define DAC_to_ADC_0_INIT_DRIVESTATE 1u
#define DAC_to_ADC_0_INIT_MUXSEL 0u
#define DAC_to_ADC_0_INPUT_SYNC 2u
#define DAC_to_ADC_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DAC_to_ADC_0_NUM 1u
#define DAC_to_ADC_0_PORT GPIO_PRT10
#define DAC_to_ADC_0_SLEWRATE CY_GPIO_SLEW_FAST
#define DAC_to_ADC_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define DAC_to_ADC_DRIVEMODE CY_GPIO_DM_ANALOG
#define DAC_to_ADC_INBUF_ENABLED 0u
#define DAC_to_ADC_INIT_DRIVESTATE 1u
#define DAC_to_ADC_INIT_MUXSEL 0u
#define DAC_to_ADC_INPUT_SYNC 2u
#define DAC_to_ADC_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define DAC_to_ADC_NUM 1u
#define DAC_to_ADC_PORT GPIO_PRT10
#define DAC_to_ADC_SLEWRATE CY_GPIO_SLEW_FAST
#define DAC_to_ADC_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
