/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_CM4_RedLED */
#define Pin_CM4_RedLED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM4_RedLED_0_INBUF_ENABLED 0u
#define Pin_CM4_RedLED_0_INIT_DRIVESTATE 1u
#define Pin_CM4_RedLED_0_INIT_MUXSEL 0u
#define Pin_CM4_RedLED_0_INPUT_SYNC 2u
#define Pin_CM4_RedLED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM4_RedLED_0_NUM 3u
#define Pin_CM4_RedLED_0_PORT GPIO_PRT6
#define Pin_CM4_RedLED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM4_RedLED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_CM4_RedLED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM4_RedLED_INBUF_ENABLED 0u
#define Pin_CM4_RedLED_INIT_DRIVESTATE 1u
#define Pin_CM4_RedLED_INIT_MUXSEL 0u
#define Pin_CM4_RedLED_INPUT_SYNC 2u
#define Pin_CM4_RedLED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM4_RedLED_NUM 3u
#define Pin_CM4_RedLED_PORT GPIO_PRT6
#define Pin_CM4_RedLED_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM4_RedLED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_CM0p_BlueLED */
#define Pin_CM0p_BlueLED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM0p_BlueLED_0_INBUF_ENABLED 0u
#define Pin_CM0p_BlueLED_0_INIT_DRIVESTATE 1u
#define Pin_CM0p_BlueLED_0_INIT_MUXSEL 0u
#define Pin_CM0p_BlueLED_0_INPUT_SYNC 2u
#define Pin_CM0p_BlueLED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM0p_BlueLED_0_NUM 1u
#define Pin_CM0p_BlueLED_0_PORT GPIO_PRT7
#define Pin_CM0p_BlueLED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM0p_BlueLED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_CM0p_BlueLED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_CM0p_BlueLED_INBUF_ENABLED 0u
#define Pin_CM0p_BlueLED_INIT_DRIVESTATE 1u
#define Pin_CM0p_BlueLED_INIT_MUXSEL 0u
#define Pin_CM0p_BlueLED_INPUT_SYNC 2u
#define Pin_CM0p_BlueLED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_CM0p_BlueLED_NUM 1u
#define Pin_CM0p_BlueLED_PORT GPIO_PRT7
#define Pin_CM0p_BlueLED_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_CM0p_BlueLED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
