/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED */
#define LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_0_INBUF_ENABLED 0u
#define LED_0_INIT_DRIVESTATE 1u
#define LED_0_INIT_MUXSEL 0u
#define LED_0_INPUT_SYNC 2u
#define LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_0_NUM 3u
#define LED_0_PORT GPIO_PRT0
#define LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_INBUF_ENABLED 0u
#define LED_INIT_DRIVESTATE 1u
#define LED_INIT_MUXSEL 0u
#define LED_INPUT_SYNC 2u
#define LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_NUM 3u
#define LED_PORT GPIO_PRT0
#define LED_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
